import {bmi,weeklySummary} from './metrics.js';
import {parseDuration,formatDuration} from './ocr-parser.js';
import {mountImport} from './import.js';
import {mountCalendar} from './calendar.js';
import {mountDailyJournal} from './journal.js';
import {iconify} from './icons.js';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data;try{data=JSON.parse(localStorage.getItem('stride-v1'))}catch{}data??={sessions:[],measurements:[],photos:[],height:null};
let calendarController=null,journalController=null;
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',4000)}
function save(){try{localStorage.setItem('stride-v1',JSON.stringify(data));return true}catch{toast('Storage is full. Remove a photo to free up space.');return false}}
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
$('#today').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}).toUpperCase();
const views={dashboard:['Your week, in motion.','A little effort. A little progress. Every day.'],activities:['Activities','Your runs, your workouts, and the moments in between.'],progress:['Your progress','Check in with yourself. See how far you have come.'],photos:['Daily log','Your days, your photos, your progress. A little moment at a time.']};
function view(id){$('.week-label').hidden=id!=='dashboard';document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==id);document.querySelectorAll('nav button').forEach(el=>el.classList.toggle('active',el.dataset.view===id));$('#title').innerHTML=id==='dashboard'?'Your week, <span>in motion.</span>':esc(views[id][0]);$('#subtitle').textContent=views[id][1];$('#page-label').textContent=id==='dashboard'?'OVERVIEW':id==='photos'?'DAILY LOG':id.toUpperCase()}
document.querySelectorAll('[data-view]').forEach(el=>el.onclick=()=>view(el.dataset.view));
if($('.brand'))$('.brand').onclick=e=>{e.preventDefault();view('dashboard')};
function activityList(items){
 if(!items.length)return '<div class="empty"><div class="empty-icon">↗</div><div class="empty-copy"><h4>Your first session starts here</h4><p>Turn a workout screenshot into a memory, or log a session yourself.</p></div><div class="empty-actions"><button class="primary" data-empty-action="scan">Scan a screenshot</button><button class="text-button" data-empty-action="log">Log a session ↗</button></div></div>';
 return items.map(s=>{
  const seconds=s.durationSeconds??s.minutes*60;
  const pace=s.paceSeconds??(s.distance>0?seconds/s.distance:null);
  const date=new Date(s.date+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});
  const metrics=[['TIME',formatDuration(seconds)||'—',''],...(s.type==='Run'?[['DISTANCE',Number(s.distance).toFixed(2),'km'],['PACE',formatDuration(pace)||'—',pace==null?'':'/km']]:[]),['CALORIES',s.calories==null?'—':esc(s.calories),s.calories==null?'':'kcal']];
  return `<article class="activity ${s.type==='Run'?'activity-run':'activity-gym'}"><div class="activity-top"><div class="activity-icon">${s.type==='Run'?'↗':'▥'}</div><div class="activity-detail"><b>${esc(s.title)}</b><small>${esc(s.type==='Run'?'Run':'Weight training')} <span aria-hidden="true">·</span> ${esc(date)}</small></div><button class="delete" data-delete="${esc(s.id)}" aria-label="Delete ${esc(s.title)}">×</button></div><div class="activity-metrics">${metrics.map(([label,value,unit])=>`<div class="activity-metric"><span class="metric-label">${label}</span><strong>${value}${unit?` <small class="metric-unit">${unit}</small>`:''}</strong></div>`).join('')}</div>${s.notes?`<p class="activity-notes">${esc(s.notes)}</p>`:''}</article>`;
 }).join('')
}
function render(){const w=weeklySummary(data.sessions);$('#stats').innerHTML=[['Sessions',w.count,'','Activities this week','◈'],['Time moving',Math.round(w.minutes),'min','Every minute adds up','◷'],['Distance',w.distance.toFixed(1),'km','Running this week','↗'],['Gym sessions',w.gym,'','Time to get stronger','▥']].map(([label,value,unit,sub,icon])=>`<div class="stat"><div class="stat-top">${label}<span class="stat-icon">${icon}</span></div><strong>${value} <small>${unit}</small></strong><small>${sub}</small></div>`).join('');
const start=new Date();start.setHours(0,0,0,0);start.setDate(start.getDate()-((start.getDay()+6)%7));const days=Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return data.sessions.filter(s=>new Date(s.date+'T00:00:00').getTime()===d.getTime()).reduce((sum,s)=>sum+Number(s.minutes),0)});const max=Math.max(...days,60);$('#week-chart').innerHTML=days.map((n,i)=>`<div class="day${i===(new Date().getDay()+6)%7?' is-today':''}" title="${Math.round(n)} minutes"><div class="bar" style="height:${n/max*100}%"></div><span>${['MON','TUE','WED','THU','FRI','SAT','SUN'][i]}</span></div>`).join('');
if($('#week-range')){const end=new Date(start);end.setDate(end.getDate()+6);$('#week-range').textContent=`${start.toLocaleDateString(undefined,{month:'short',day:'numeric'})} – ${end.toLocaleDateString(undefined,{month:'short',day:'numeric'})}`}
if($('#weekly-total'))$('#weekly-total').innerHTML=`${Math.round(w.minutes)} <small>minutes moving</small>`;
$('#review').textContent=w.count?`You showed up ${w.count} time${w.count===1?'':'s'} this week, with ${Math.round(w.minutes)} minutes of movement. ${w.distance?`${w.distance.toFixed(1)} km on your feet. `:''}${w.gym?`${w.gym} gym session${w.gym===1?'':'s'} logged. `:''}Make space for recovery as well as your next session.`:'A fresh week, a fresh start. Log your first session and your weekly review will take shape here.';
const last=data.measurements.at(-1), value=last?bmi(last.weight,data.height):null;$('#bmi-value').innerHTML=`${value?value.toFixed(1):'—'} <small>BMI</small>`;$('#body-summary').textContent=last?`${last.weight} kg · ${data.height} cm · ${value<18.5?'Below typical adult range':value<25?'Within typical adult range':value<30?'Above typical adult range':'High adult BMI range'}`:'Add your height and weight to see your BMI.';
if($('#weight-value'))$('#weight-value').innerHTML=`${last?esc(last.weight):'—'} <small>kg</small>`;
if($('#height-value'))$('#height-value').innerHTML=`${data.height?esc(data.height):'—'} <small>cm</small>`;
const sorted=[...data.sessions].sort((a,b)=>b.date.localeCompare(a.date));$('#recent').innerHTML=activityList(sorted.slice(0,4));$('#all-activities').innerHTML=activityList(sorted.filter(s=>$('#filter').value==='All activities'||s.type===$('#filter').value));
$('#weight-history').innerHTML=data.measurements.length?[...data.measurements].reverse().map(m=>`<div class="activity measurement"><div class="activity-top"><div class="activity-icon">◎</div><div class="activity-detail"><b>${esc(m.weight)} kg</b><small>${esc(new Date(m.date+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}))}</small></div></div></div>`).join(''):'<div class="empty"><div class="empty-icon">◎</div><div class="empty-copy"><h4>Start with a check-in</h4><p>Add your height and weight to see your BMI and build your history.</p></div><button class="text-button" data-empty-action="measure">Add measurements ↗</button></div>';
document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Delete this activity?')){data.sessions=data.sessions.filter(s=>s.id!==b.dataset.delete);save();render()}});document.querySelectorAll('[data-empty-action]').forEach(b=>b.onclick=()=>{switch(b.dataset.emptyAction){case 'scan':openScan();break;case 'photo':view('photos');journalController?.openComposer();break;case 'measure':view('progress');$('#body-form').elements.height.focus();break;default:openActivity()}});iconify(document.body);calendarController?.refresh();window.dispatchEvent(new CustomEvent('stride-activities-changed'))}
$('#filter').onchange=render;
function openActivity(){const f=$('#activity-form');f.reset();f.elements.date.value=localDate();updateType();$('#activity-dialog').showModal()}
function openScan(){view('activities');$('#session-photo').click()}
$('#add-top').onclick=openActivity;$('#hero-log').onclick=openScan;$('#close-dialog').onclick=()=>$('#activity-dialog').close();
if($('#dashboard-scan'))$('#dashboard-scan').onclick=openScan;
if($('#dashboard-log'))$('#dashboard-log').onclick=openActivity;
if($('#dashboard-run'))$('#dashboard-run').onclick=()=>{view('activities');$('#gps-panel').scrollIntoView({behavior:'smooth',block:'center'});$('#gps-start').focus({preventScroll:true})};
if($('#dashboard-calendar'))$('#dashboard-calendar').onclick=()=>$('nav [data-view="calendar"]').click();
function updateType(){const run=$('#activity-form').elements.type.value==='Run';$('#distance-label').hidden=!run;$('#pace-label').hidden=!run;$('#activity-form').elements.distance.required=run}
$('#activity-form').elements.type.onchange=updateType;
$('#activity-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),durationSeconds=parseDuration(f.get('duration')),pace=f.get('pace').trim(),paceSeconds=pace?parseDuration(pace):null;if(!durationSeconds||durationSeconds>86400||(f.get('type')==='Run'&&pace&&(!paceSeconds||!/^\d+:\d{2}$/.test(pace)))){toast('Use a valid duration and pace, such as 17:53 or 6:51.');return}const session={id:crypto.randomUUID(),type:f.get('type'),title:f.get('title').trim(),date:f.get('date'),durationSeconds,minutes:durationSeconds/60,distance:f.get('type')==='Run'?Number(f.get('distance')):0,paceSeconds:f.get('type')==='Run'?(paceSeconds??durationSeconds/Number(f.get('distance'))):null,calories:f.get('calories')===''?null:Number(f.get('calories')),notes:f.get('notes').trim()};if(!session.title||session.date>localDate()){toast('Enter a name and a date on or before today.');return}data.sessions.push(session);if(!save()){data.sessions.pop();return}$('#activity-dialog').close();render();toast('Activity saved. Keep showing up!')};
$('#body-form').elements.height.value=data.height||'';$('#body-form').elements.weight.value=data.measurements.at(-1)?.weight||'';
$('#body-form').onsubmit=e=>{e.preventDefault();const previous=data.height;data.height=Number(e.target.elements.height.value);data.measurements.push({weight:Number(e.target.elements.weight.value),date:localDate()});if(!save()){data.measurements.pop();data.height=previous;return}render();toast('Measurements saved')};
const panel=document.createElement('div');panel.id='gps-panel';panel.innerHTML='<div class="gps-panel-copy"><span class="eyebrow">FRESH AIR, FRESH START</span><h3>Let’s go for a run</h3><p id="gps-status" aria-live="polite">Track your time, distance and pace with live GPS.</p><small class="note">Location permission required. Keep this screen open while running.</small></div><div class="gps-panel-actions"><button class="gps-action" id="gps-start">Start run ↗</button><button class="gps-action" id="gps-stop" hidden>Finish & save</button></div>';
$('#activities').prepend(panel);
let watch=null,timer=null,started=0,distance=0,previous=null;
function kilometers(a,b){const rad=x=>x*Math.PI/180;const dlat=rad(b.latitude-a.latitude),dlon=rad(b.longitude-a.longitude);const h=Math.sin(dlat/2)**2+Math.cos(rad(a.latitude))*Math.cos(rad(b.latitude))*Math.sin(dlon/2)**2;return 6371*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}
function gpsStatus(){const sec=Math.floor((Date.now()-started)/1000);$('#gps-status').textContent=`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')} elapsed · ${distance.toFixed(2)} km · Keep this screen open`}
function endGps(){if(watch!==null)navigator.geolocation.clearWatch(watch);watch=null;clearInterval(timer);$('#gps-start').hidden=false;$('#gps-stop').hidden=true}
$('#gps-start').onclick=()=>{if(!navigator.geolocation){toast('Location tracking is unavailable in this browser.');return}if(!window.isSecureContext){toast('GPS needs HTTPS. You can still log runs manually.');return}started=Date.now();distance=0;previous=null;$('#gps-start').hidden=true;$('#gps-stop').hidden=false;$('#gps-status').textContent='Finding your location…';watch=navigator.geolocation.watchPosition(p=>{if(p.coords.accuracy>50){$('#gps-status').textContent='Waiting for a more accurate GPS signal…';return}const point={latitude:p.coords.latitude,longitude:p.coords.longitude,time:p.timestamp};if(previous){const delta=kilometers(previous,point),seconds=(point.time-previous.time)/1000;if(seconds>0&&delta/seconds<.015)distance+=delta}previous=point;gpsStatus();if(!timer)timer=setInterval(gpsStatus,1000)},err=>{endGps();$('#gps-status').textContent=err.code===1?'Location permission denied. Enable location access to track a run.':'GPS unavailable. Try again outside with a clear signal.'},{enableHighAccuracy:true,maximumAge:0,timeout:20000})};
$('#gps-stop').onclick=()=>{if(!previous){endGps();$('#gps-status').textContent='No GPS fix received. Run was not saved.';return}const durationSeconds=Math.max(1,Math.round((Date.now()-started)/1000));const session={id:crypto.randomUUID(),type:'Run',title:'GPS run',date:localDate(),durationSeconds,minutes:durationSeconds/60,distance:Number(distance.toFixed(3)),paceSeconds:distance>0?durationSeconds/distance:null,calories:null,notes:'Recorded with live GPS; calories not measured'};data.sessions.push(session);if(!save()){data.sessions.pop();return}endGps();$('#gps-status').textContent=`Run saved · ${distance.toFixed(2)} km`;render();toast('Your run is saved')};
window.addEventListener('beforeunload',e=>{if(watch!==null){e.preventDefault();e.returnValue=''}});
mountImport($('#activities'),{esc,toast,localDate,onSave:sessions=>{const previous=[...data.sessions];data.sessions.push(...sessions);if(!save()){data.sessions=previous;return false}render();return true}});
journalController=mountDailyJournal($('#daily-journal'),{esc,toast,localDate,legacyPhotos:data.photos||[]});
calendarController=mountCalendar({esc,toast,localDate,getSessions:()=>data.sessions,getPosts:()=>journalController.getPosts()});
window.addEventListener('stride-journal-changed',()=>calendarController?.refresh());
render();
