import {parseCalendar,gymBooking,dueReminders} from './calendar-parser.js';
export function mountCalendar({esc,toast,localDate}){
 const calendarIcon='<svg class="inline-icon" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M16 3v4M8 3v4M3 11h18M8 15h3"/></svg>';
 const nav=document.createElement('button');nav.dataset.view='calendar';nav.innerHTML='<svg class="icon" aria-hidden="true"><use href="#i-calendar"/></svg><span>Bookings</span>';document.querySelector('nav').append(nav);
 const section=document.createElement('section');section.id='calendar';section.className='view';section.hidden=true;section.innerHTML=`<div class="two-columns"><section class="card calendar-connect-card"><span class="eyebrow">YOUR PLANS, IN ONE PLACE</span><h3>Connect Apple Calendar</h3><p>Bring your gym bookings into Stride so your next session is always close by.</p><form id="calendar-connect"><label>Published iCloud calendar link<input name="url" type="text" placeholder="Paste your webcal:// calendar link" required></label><div class="calendar-form-actions"><button class="primary">Connect calendar</button><button type="button" class="text-button" id="calendar-disconnect">Disconnect</button></div></form><details class="calendar-help"><summary>How to find your calendar link</summary><p class="note">In Apple Calendar, share a separate gym calendar → enable Public Calendar → Copy Link. Anyone with that link can read the calendar. Use a separate gym calendar to keep personal events private.</p><p class="note">Published calendars refresh every 15 minutes while Stride is open.</p></details><div class="calendar-import-row"><label class="text-button upload">Import a private .ics file<input id="ics-input" type="file" accept=".ics,text/calendar" hidden></label><button id="calendar-refresh" class="text-button">Refresh ↻</button></div><details class="calendar-help"><summary>Prefer a private calendar export?</summary><p class="note">In Calendar on Mac, choose File → Export → Export. File imports do not sync automatically; import a new file when bookings change.</p></details><p id="calendar-status" role="status"></p></section><section class="card calendar-reminders-card"><span class="eyebrow">A LITTLE NUDGE</span><h3>Make it to your next class</h3><p>Choose when you would like a reminder.</p><label>Remind me before class<select id="reminder-lead"><option value="15">15 minutes</option><option value="30">30 minutes</option><option value="60">1 hour</option><option value="120">2 hours</option></select></label><button class="primary" id="notifications-enable">Enable notifications</button><p id="notification-status" class="note"></p><p class="note">Keep Stride open to receive reminders. For alerts when your screen is asleep or the app is closed, use Apple Calendar alerts.</p></section></div><section class="card"><div class="section-head"><div><span class="eyebrow">ON YOUR CALENDAR</span><h3>Upcoming bookings</h3></div><label class="inline-label"><input id="gym-only" type="checkbox" checked> Gym & fitness only</label></div><div id="bookings"></div></section>`;
 document.querySelector('footer').before(section);const $=s=>section.querySelector(s);
 let state;try{state=JSON.parse(localStorage.getItem('stride-calendar'))}catch{}state??={url:'',events:[],lead:30,notified:[],source:''};state.notified??=[];
 const persist=()=>{try{localStorage.setItem('stride-calendar',JSON.stringify(state));return true}catch{toast('Unable to save calendar. Free some browser storage.');return false}};
 $('#reminder-lead').value=state.lead;$('#calendar-connect input').value=state.url;
 nav.onclick=()=>{document.querySelector('.week-label').hidden=true;document.querySelectorAll('.view').forEach(v=>v.hidden=v!==section);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b===nav));document.querySelector('#title').textContent='Your bookings';document.querySelector('#subtitle').textContent='A place for your plans. A nudge to keep them.';document.querySelector('#page-label').textContent='BOOKINGS'};
 function render(){
  const upcoming=state.events.filter(e=>new Date(e.start)>=new Date()).sort((a,b)=>new Date(a.start)-new Date(b.start));
  const events=upcoming.filter(e=>!$('#gym-only').checked||gymBooking(e));
  const dateText=e=>new Date(e.start).toLocaleString(undefined,e.allDay?{dateStyle:'medium'}:{dateStyle:'medium',timeStyle:'short'})+(e.allDay?' · All day':'');
  $('#bookings').innerHTML=events.length?events.map(e=>`<article class="activity booking"><div class="activity-top"><div class="activity-icon">${calendarIcon}</div><div class="activity-detail"><b>${esc(e.title)}</b><small>${esc(dateText(e))}</small><small>${esc(e.location||'Location not specified')}</small></div><span class="badge">${e.allDay?'ALL DAY':Math.ceil((new Date(e.start)-new Date())/3600000)+' HRS AWAY'}</span></div></article>`).join(''):`<div class="empty"><div class="empty-icon">${calendarIcon}</div><div class="empty-copy"><h4>${state.source?'Your calendar has some breathing room':'Your next class belongs here'}</h4><p>${state.source?'No upcoming bookings match this view. Refresh your calendar or import your latest bookings.':'Connect a gym calendar, or import a private .ics file to see your bookings.'}</p></div>${state.source?'':'<button class="primary" data-calendar-connect>Connect Apple Calendar</button>'}</div>`;
  const nextBlock=document.querySelector('#next-booking');
  if(nextBlock){const next=upcoming.find(gymBooking);nextBlock.innerHTML=next?`<span class="next-booking-label eyebrow">NEXT UP</span><h3 class="next-booking-title">${esc(next.title)}</h3><p class="next-booking-meta">${esc(dateText(next))}${next.location?`<span>${esc(next.location)}</span>`:''}</p>`:`<span class="next-booking-label eyebrow">YOUR NEXT SESSION</span><h3 class="next-booking-title">${state.source?'A little room to make plans.':'Save a spot for yourself.'}</h3><p class="next-booking-meta">${state.source?'No upcoming gym bookings. Your next class will appear here.':'Connect Apple Calendar to see your gym bookings and get a reminder.'}</p><button class="text-button" data-calendar-connect>${state.source?'View your bookings':'Connect Apple Calendar'} ↗</button>`}
  document.querySelectorAll('[data-calendar-connect]').forEach(b=>b.onclick=()=>{nav.click();if(!state.source)$('#calendar-connect input').focus()});
  $('#calendar-disconnect').hidden=!state.url;$('#calendar-refresh').disabled=!state.url;
 }
 function notificationStatus(){const support='Notification' in window;$('#notification-status').textContent=!support?'Notifications are unavailable in this browser. In-app reminders still work.':Notification.permission==='granted'?'Browser notifications enabled while the app is running.':Notification.permission==='denied'?'Notifications blocked. Change this site’s browser permissions to enable them.':'Allow notifications to get an alert before your bookings.';}
 async function sync(raw=state.url){if(!raw){toast('Connect a published calendar to refresh it.');return}$('#calendar-status').textContent='Refreshing calendar…';$('#calendar-refresh').disabled=true;try{const response=await fetch('/api/calendar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:raw})});const body=await response.json();if(!response.ok)throw Error(body.error);const events=parseCalendar(body.calendar);state.url=raw;state.events=events;state.source='subscription';state.updated=new Date().toISOString();persist();$('#calendar-status').textContent=`Updated ${new Date().toLocaleTimeString()} · ${events.length} events in the next 90 days`;render();checkReminders()}catch(err){$('#calendar-status').textContent=err.message||'Calendar sync failed. Existing bookings were kept.'}finally{$('#calendar-refresh').disabled=!state.url}}
 $('#calendar-connect').onsubmit=e=>{e.preventDefault();sync(e.target.elements.url.value.trim())};$('#calendar-refresh').onclick=()=>sync();
 $('#calendar-disconnect').onclick=()=>{if(confirm('Disconnect and remove imported bookings?')){state.url='';state.events=[];state.notified=[];state.source='';persist();$('#calendar-connect').reset();$('#calendar-status').textContent='Calendar disconnected.';render()}};
 $('#ics-input').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2*1024*1024)throw Error('Choose a calendar smaller than 2 MB.');const events=parseCalendar(await file.text());state.events=events;state.url='';state.source='file';state.notified=[];persist();$('#calendar-connect input').value='';$('#calendar-status').textContent=`Imported ${events.length} events. Re-import to pick up calendar changes.`;render();checkReminders()}catch(err){$('#calendar-status').textContent=err.message||'Unable to read calendar file.'}finally{e.target.value=''}};
 $('#reminder-lead').onchange=e=>{state.lead=Number(e.target.value);persist();checkReminders()};$('#gym-only').onchange=render;
 $('#notifications-enable').onclick=async()=>{if(!('Notification'in window)){toast('Browser notifications are unavailable.');return}try{await Notification.requestPermission();notificationStatus()}catch{toast('Notifications require HTTPS and browser support.')}};
 function checkReminders(){const events=state.events.filter(gymBooking),notified=new Set(state.notified);for(const event of dueReminders(events,Date.now(),state.lead,notified)){const minutes=Math.max(1,Math.ceil((new Date(event.start)-Date.now())/60000)),message=`${event.title} in ${minutes} min${event.location?' · '+event.location:''}`;toast(message);if('Notification'in window&&Notification.permission==='granted'){try{new Notification('Your gym booking is coming up',{body:message,tag:event.id})}catch{}}state.notified.push(event.id);notified.add(event.id)}state.notified=state.notified.slice(-500);persist()}
 setInterval(()=>{checkReminders();render()},30000);setInterval(()=>{if(state.url)sync()},15*60000);window.addEventListener('focus',()=>{checkReminders();if(state.url&&(!state.updated||Date.now()-new Date(state.updated)>15*60000))sync()});notificationStatus();render();checkReminders();if(state.url)sync();
}
