import {parseActivities,parseDuration,formatDuration} from './ocr-parser.js';
export function mountImport(container,{esc,toast,localDate,onSave}){
 const panel=document.createElement('section');panel.className='card import-panel scan-upload-panel';panel.innerHTML='<div class="scan-intro"><div class="scan-icon"><svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M8 3H5a2 2 0 0 0-2 2v3m13-5h3a2 2 0 0 1 2 2v3M3 16v3a2 2 0 0 0 2 2h3m8 0h3a2 2 0 0 0 2-2v-3M7 14l3-3 3 3 2-2 2 2"/><circle cx="15" cy="8" r="1"/></svg></div><div class="scan-copy"><span class="eyebrow">LESS TYPING. MORE MOVING.</span><h3>Your screenshot. Your session.</h3><p>Upload a workout screenshot. We’ll find your runs and gym sessions, even when there’s more than one.</p></div><label class="primary upload scan-upload-action">Scan a screenshot<input id="session-photo" type="file" accept="image/*" hidden></label></div><ol class="scan-steps"><li><span>1</span> Upload a screenshot</li><li><span>2</span> Check the details</li><li><span>3</span> Save your sessions</li></ol><p class="note scan-note">Processed on your device. Clear text works best. Missing numbers stay blank.</p><p id="scan-status" role="status"></p><div id="scan-result"></div>';
 container.prepend(panel);const input=panel.querySelector('input'),status=panel.querySelector('#scan-status'),results=panel.querySelector('#scan-result');
 let worker=null,busy=false;
 function showReview(activities,text){
  results.innerHTML=`<div class="scan-review-head"><h4>${activities.length?`${activities.length} session${activities.length===1?'':'s'} found`:'Let’s add the details'}</h4><p>${activities.length?'Check the numbers and dates below before adding these to your history.':'No sessions confidently detected. Add one below or try a clearer screenshot.'}</p></div><form id="review-import"><div id="import-rows"></div><button type="button" class="text-button" id="add-import-row">＋ Add a missing session</button><p class="note">Confirm the date for each session. Dates are not inferred from screenshot captions. Blank calories remain unknown; pace can be calculated from duration and distance.</p><button class="primary" id="save-import">Save reviewed sessions</button></form><details class="scan-text-details"><summary>View detected text</summary><pre id="ocr-text"></pre></details>`;
  results.querySelector('#ocr-text').textContent=text;
  const rows=results.querySelector('#import-rows');let sequence=0;
  function addRow(a={type:'Run'}){const row=document.createElement('fieldset');row.className='import-row';row.innerHTML=`<legend>Session ${++sequence}</legend><div class="section-head"><label>Activity<select name="type"><option ${a.type==='Run'?'selected':''}>Run</option><option ${a.type==='Gym'?'selected':''}>Gym</option></select></label><button type="button" class="delete" aria-label="Remove detected session">Remove ×</button></div><label>Name<input name="title" value="${esc(a.title||'')}" maxlength="100" required></label><div class="form-row"><label>Date<input name="date" type="date" value="${localDate()}" max="${localDate()}" required></label><label>Duration (mm:ss or 1h 2m)<input name="duration" value="${formatDuration(a.durationSeconds)}" placeholder="Missing — enter time" required></label></div><div class="form-row run-fields"><label>Distance (km)<input name="distance" type="number" min="0.01" max="1000" step="0.01" value="${a.distance??''}" placeholder="Missing"></label><label>Pace (min:sec / km)<input name="pace" value="${formatDuration(a.paceSeconds)}" placeholder="Calculated if blank"></label></div><label>Calories (kcal)<input name="calories" type="number" min="0" max="20000" step="1" value="${a.calories??''}" placeholder="Not detected — optional"></label>`;
   rows.append(row);row.querySelector('.delete').onclick=()=>row.remove();const select=row.querySelector('select');const update=()=>{const run=select.value==='Run';row.querySelector('.run-fields').hidden=!run;row.querySelector('[name=distance]').required=run};select.onchange=update;update();}
  activities.forEach(addRow);results.querySelector('#add-import-row').onclick=()=>addRow();results.querySelector('form').onsubmit=e=>{e.preventDefault();const sessions=[];for(const row of rows.children){const get=name=>row.querySelector(`[name=${name}]`).value;const seconds=parseDuration(get('duration')),pace=get('pace'),paceSeconds=pace?parseDuration(pace):null;if(!seconds||seconds>86400||(get('type')==='Run'&&pace&&(!paceSeconds||!/^\d+:\d{2}$/.test(pace)))){toast('Check duration and pace. Use mm:ss, such as 17:53.');return}if(!get('title').trim()){toast('Enter a session name.');return}const distance=get('type')==='Run'?Number(get('distance')):0;sessions.push({id:crypto.randomUUID(),type:get('type'),title:get('title').trim(),date:get('date'),durationSeconds:seconds,minutes:seconds/60,distance,paceSeconds:get('type')==='Run'?(paceSeconds??seconds/distance):null,calories:get('calories')===''?null:Number(get('calories')),notes:'Imported from workout screenshot'})}if(!sessions.length){toast('Add a session to import.');return}if(onSave(sessions)){results.innerHTML='';status.textContent=`${sessions.length} sessions saved.`;toast('Screenshot sessions logged')}};
 }
 input.onchange=async()=>{const file=input.files[0];if(!file||busy)return;busy=true;input.disabled=true;results.innerHTML='';try{if(!file.type.startsWith('image/'))throw Error('Choose an image file.');if(file.size>20*1024*1024)throw Error('Choose a screenshot under 20 MB.');status.textContent='Loading text recognition…';worker??=await window.Tesseract.createWorker('eng',1,{workerPath:'/ocr/worker.min.js',corePath:'/ocr/core',langPath:'/ocr/lang',gzip:false,logger:m=>{if(m.status==='recognizing text')status.textContent=`Reading screenshot… ${Math.round(m.progress*100)}%`}});const result=await worker.recognize(file);const activities=parseActivities(result.data.text);status.textContent=`${activities.length} possible session${activities.length===1?'':'s'} detected. Check each value below.`;showReview(activities,result.data.text)}catch(error){console.error(error);status.textContent='Unable to scan this image. Try a clearer screenshot, or enter the session manually.';toast('Screenshot recognition failed.')}finally{input.value='';input.disabled=false;busy=false}};
}
